name: Lynn Aineomugisha, Participant at Powercoders
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
#gems: "jekyll-paginate"
gems: 
- jekyll-paginate

paginate:    4
paginate_path: "blog/page:num"
